### ISSUE TITLE
Documentation of the Nreal USB HID Report formats?

### ISSUE THREAD

**Issue by datenwolf** [badicsalex/ar-drivers-rs#1]
Is there an outside-of-source documentation of the Nreal HID Report formats? Could be something as simple as "sketches on a napkin".

I just got a Nreal Light and would like to compare my reverse engineering efforts on its HID reports with what you might have written down. Preferably without piecing it together from the parser code.

**Comment by badicsalex** [comment]
Hi,

I actually made a blogpost about these: https://voidcomputing.hu/blog/good-bad-ugly/

Does this help?

**Comment by datenwolf** [comment]
Wow, that's more than I could've asked for. Bonus points for cute dog!

**Comment by datenwolf** [comment]
I do hope the comment on Rust is not on my behalf ;-)

I do love the language (however I don't like some of the design choices of Cargo).
